### ISSUE TITLE
Different behaviour between CI and local machine

### ISSUE THREAD

**Issue by Evleaps** [dropbox/AffectedModuleDetector#140]
Hi! Please, help me with setup AMD on the CI. 

According to a AMD log file a lot of modules on the CI marked as true, but on the local machine the modules marked as false. 
**command**: `./gradlew runAffectedUnitTests -Paffected_module_detector.enable -Pci=true --scan`

**Environment:**
Doker + GitHub actions

**Changed files:**
Only 1 changed file for test with minor syntax change in feature module.

**Expected result:** Only few modules was affected. 
**Actual result:** 89 modules was affected on the CI. 

**Example:** 
CI machine - 89 modules affected (true) 23 modules is not affected (false)
Local machine - only 3 modules affected (true) 109 modules is not affected (false) 

Hence, build time on the CI is not efficent. 

**build.gradle**
```groovy
affectedModuleDetector {
    baseDir = "${project.rootDir}"
    pathsAffectingAllModules = []
    logFolder = "${project.rootDir}/tools/impact-analysis/output"
    excludedModules = [
        "appLint"
    ]
    specifiedBranch = "origin/dev"
    compareFrom = "SpecifiedBranchCommit"
    includeUncommitted = false
}
```

**CI:** github workflow
```yml
  unit-test_by_impact:
    runs-on: [ some-build ]
    if: ${{ !startsWith(github.head_ref, 'release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Fetch dev'
        run: git fetch origin dev:dev
      - name: 'Run unit tests by impact'
        run: |
          source ./ci/_builder_docker.sh
          runInContainer "./ci/unit_tests_by_impact.sh"
      - name: 'Upload test_by_impact log file'
        uses: actions/upload-artifact@v2
        with:
          name: test_by_impact-log-${{ github.run_number }}
          path: tools/impact-analysis/output
          retention-days: 1
```
